force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsTreeViewControllerTest.cls
@isTest
class BracketsTreeViewControllerTest {
    @isTest
    static void testConstructors() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c groupp = BracketsTestUtilities.getGroup(
            tournament.Id
        );
        Brackets_UserTournament__c userTournament = BracketsTestUtilities.createUserTournament(
            Userinfo.getUserId(),
            tournament.Id,
            groupp.Id
        );

        //constructor without parameters

        BracketsTreeViewController controller = new BracketsTreeViewController();
        controller.groupId = groupp.Id;
        controller.isLocked = false;

        System.assert(controller.getIsRenderable());

        System.assert(controller.tournamentId == tournament.Id);

        System.assert(controller.nflTree == null);
        System.assert(controller.stdTree != null);
    }
}