force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/Brackets_Round__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Round__c</fullName>
    <label>Round</label>
    <referenceTo>Brackets_Round__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/Brackets_Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/Brackets_UserMatchPred__c.object-meta.xml
<CustomObject>
    <label>UserMatchPrediction</label>
    <nameField>
        <displayFormat>UMP-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserMatchPredictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_Match__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Match__c</fullName>
    <label>Match</label>
    <referenceTo>Brackets_Match__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_UserTournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_UserTournament__c</fullName>
    <label>UserTournament</label>
    <referenceTo>Brackets_UserTournament__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsTestUtilitiesTest.cls
@isTest
class BracketsTestUtilitiesTest {
    @isTest
    static void testRandomWord() {
        System.assert(
            BracketsTestUtilities.createRandomWord() !=
            BracketsTestUtilities.createRandomWord()
        );
    }

    @isTest
    static void testCreateUser() {
        User u = BracketsTestUtilities.createUser();
        system.assert(u != null);
        system.assert(u.Id != null);
    }

    @isTest
    static void testCreateAndUpsertTeam() {
        Brackets_Team__c team = BracketsTestUtilities.createTeam('MyTeam');
        system.assert(team != null);
        system.assert(team.Name == 'MyTeam');
    }

    @isTest
    static void testCreateTeamList() {
        List<Brackets_Team__c> someTeams = BracketsTestUtilities.createTeamList(
            4
        );
        system.assert(someTeams.size() == 4);
    }

    @isTest
    static void testGetRandomTeam() {
        List<Brackets_Team__c> teams = BracketsTestUtilities.createTeamList(2);

        upsert teams;

        Brackets_Team__c t = BracketsTestUtilities.getRandomTeam(teams);
        system.assert(t != null);
        system.assert(t.Name != null && t.Name != '');
    }

    @isTest
    static void testCreateTournamet() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Tournament-',
            2
        );
        system.assert(tournament != null);
    }

    @isTest
    static void testCreateRound() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Tournament-',
            2
        );
        Brackets_Round__c round = BracketsTestUtilities.createSimpleRound(
            tournament
        );
        system.assert(round != null);
    }

    @isTest
    static void testCreateMatch() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Tournament-',
            2
        );
        Brackets_Round__c round = BracketsTestUtilities.createSimpleRound(
            tournament
        );
        Brackets_Match__c match = BracketsTestUtilities.createMatch(
            null,
            null,
            round,
            null
        );

        system.assert(match != null);
    }

    @isTest
    static void testCreateUserTournamet() {
        User user = BracketsTestUtilities.createUser();
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Tournament-',
            2
        );
        Brackets_Group__c groupp = BracketsTestUtilities.getGroup(
            tournament.Id
        );
        Brackets_UserTournament__c ut = BracketsTestUtilities.createUserTournament(
            user.Id,
            tournament.Id,
            groupp.Id
        );
        system.assert(ut != null);
    }

    @isTest
    static void testCreateUserMatchPrediction() {
        User user = BracketsTestUtilities.createUser();
        Brackets_Tournament__c tournament = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c uGroup = BracketsTestUtilities.getGroup(
            tournament.Id
        );
        Brackets_UserTournament__c ut = BracketsTestUtilities.createUserTournament(
            user.Id,
            tournament.Id,
            uGroup.Id
        );
        Brackets_Round__c round = BracketsTestUtilities.createSimpleRound(
            tournament
        );
        List<Brackets_Team__c> teams = BracketsTestUtilities.createTeamList(2);

        Brackets_Team__c home = teams[0];
        Brackets_Team__c visitor = teams[1];
        upsert teams;

        Brackets_Match__c match = BracketsTestUtilities.createMatch(
            home,
            visitor,
            round,
            null
        );
        Brackets_Team__c winner = home;

        BracketsTestUtilities.createUserMatchPrediction(
            tournament.Id,
            uGroup.Id,
            ut.Id
        );

        List<Brackets_UserMatchPred__c> predictions = [
            SELECT Id
            FROM Brackets_UserMatchPred__c
            WHERE Brackets_UserTournament__c = :ut.Id
        ];
        system.assert(!predictions.isEmpty(), predictions);
    }

    @isTest
    static void testCreateFullTournament() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createFullTournament(
            4,
            BracketsTournamentUtilities.DEFAULT_TOURNAMENT_TYPE
        );
        system.assert(tournament != null);
    }
}