force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/HomeBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>HomeBrackets_Team__c</fullName>
    <label>Team 1</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>HomeMatches</relationshipLabel>
    <relationshipName>HomeMatch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/Brackets_UserMatchPred__c.object-meta.xml
<CustomObject>
    <label>UserMatchPrediction</label>
    <nameField>
        <displayFormat>UMP-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserMatchPredictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_Match__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Match__c</fullName>
    <label>Match</label>
    <referenceTo>Brackets_Match__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_UserTournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_UserTournament__c</fullName>
    <label>UserTournament</label>
    <referenceTo>Brackets_UserTournament__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/PredictedWinnerBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>PredictedWinnerBrackets_Team__c</fullName>
    <label>PredictedWinnerTeam</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsMatchesPredictionUtilTest.cls
@isTest
class BracketsMatchesPredictionUtilTest {
    //Test checkExistingPredictions()
    @isTest
    static void testCheckExistingPredictions() {
        //generate Enviroment
        Brackets_Tournament__c myTour = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c myGroup = BracketsTestUtilities.getGroup(myTour.Id);
        Brackets_UserTournament__c uTour = BracketsTestUtilities.createUserTournament(
            UserInfo.getUserId(),
            myTour.Id,
            myGroup.Id
        );
        BracketsTestUtilities.createUserMatchPrediction(
            myTour.Id,
            myGroup.Id,
            uTour.Id
        );
        List<Brackets_UserMatchPred__c> uMatchPred = [
            SELECT
                u.Id,
                u.Brackets_UserTournament__c,
                u.PredictedWinnerBrackets_Team__c,
                u.Brackets_Match__r.HomeBrackets_Team__c,
                u.Brackets_Match__c
            FROM Brackets_UserMatchPred__c u
            WHERE u.Brackets_UserTournament__c = :uTour.Id
        ];

        BracketsMatchesPredictionUtil.checkExistingPredictions(
            uMatchPred,
            Userinfo.getUserId()
        );
        System.assert(myTour != null);

        BracketsMatchesPredictionUtil.save(uMatchPred);
    }
}