force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsJoinInvitedUserTest.cls
@isTest
class BracketsJoinInvitedUserTest {
    //Test Join Successfully
    @isTest
    static void test() {
        //Create enviroment
        Brackets_Group__c mGroup = BracketsTestUtilities.getGroup(null);
        Apexpages.currentPage().getParameters().put('gId', mGroup.Id);
        BracketsJoinInvitedUser cTest = new BracketsJoinInvitedUser();
        Test.startTest();
        Pagereference tRef = cTest.index();
        tRef = cTest.cancel();
        tRef = cTest.joinUser();
        Test.stopTest();
        List<Brackets_UserTournament__c> uTour = [
            SELECT Id
            FROM Brackets_UserTournament__c
            WHERE
                User__c = :UserInfo.getUserId()
                AND Brackets_Group__c = :mGroup.Id
        ];
        System.assert(!uTour.isEmpty());
    }

    //Test Not URL parm
    @isTest
    static void test1() {
        //Create enviroment
        Brackets_Group__c mGroup = BracketsTestUtilities.getGroup(null);
        BracketsJoinInvitedUser cTest = new BracketsJoinInvitedUser();
        Test.startTest();
        Pagereference tRef = cTest.index();
        Test.stopTest();
        List<Brackets_UserTournament__c> uTour = [
            SELECT Id
            FROM Brackets_UserTournament__c
            WHERE
                User__c = :UserInfo.getUserId()
                AND Brackets_Group__c = :mGroup.Id
        ];
        System.assert(uTour.isEmpty());
    }

    //Test already Join
    @isTest
    static void test2() {
        //Create enviroment
        Brackets_Tournament__c mTour = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c mGroup = BracketsTestUtilities.getGroup(mTour.Id);
        Brackets_UserTournament__c uTour = BracketsTestUtilities.createUserTournament(
            Userinfo.getUserId(),
            mTour.Id,
            mGroup.Id
        );
        Apexpages.currentPage().getParameters().put('gId', mGroup.Id);

        BracketsJoinInvitedUser cTest = new BracketsJoinInvitedUser();
        Test.startTest();
        Pagereference tRef = cTest.index();
        cTest.getShowButtons();
        Test.stopTest();
        List<Brackets_UserTournament__c> uTr = [
            SELECT Id
            FROM Brackets_UserTournament__c
            WHERE
                User__c = :UserInfo.getUserId()
                AND Brackets_Group__c = :mGroup.Id
        ];
        System.assert(!uTr.isEmpty());
    }
}