force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Group__c/fields/TournamentType__c.field-meta.xml
<CustomField>
    <fullName>TournamentType__c</fullName>
    <formula>Text(Brackets_Tournament__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TournamentType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brackets_Group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText
    >Round By Round lets users predict a single round at a time.  Full Tournament requires full prediction up front and cannot be changed.</inlineHelpText>
    <label>Type</label>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Tournament</fullName>
                <default>true</default>
                <label>Full Tournament</label>
            </value>
            <value>
                <fullName>Round By Round</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText
    >Last date to make predictions for the round.</inlineHelpText>
    <label>Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/RoundNumber__c.field-meta.xml
<CustomField>
    <fullName>RoundNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Number indicating the position of the round, being 1 the first round</inlineHelpText>
    <label>Round Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText
    >Deadline for the &quot;Full tournament&quot; type pools.</inlineHelpText>
    <label>Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Which type of tournament this is?

Types supported include: &quot;NFL Playoff&quot; with fixed 12 teams and &quot;Standard&quot; a single elimination type of tournament.</inlineHelpText>
    <label>Type</label>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NFL Playoff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Championship_Point_Prediction__c.field-meta.xml
<CustomField>
    <fullName>Championship_Point_Prediction__c</fullName>
    <inlineHelpText
    >Used for breaking any ties.  Enter the total number of points scored by both teams in the championship game.</inlineHelpText>
    <label>Championship Point Prediction</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BracketsSettings2__c/BracketsSettings2__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <!-- <customSettingsVisibility>Protected</customSettingsVisibility> -->
    <label>BracketsSettings2</label>
</CustomObject>

force-app/main/default/objects/BracketsSettings2__c/fields/Hide_Help_Dialog__c.field-meta.xml
<CustomField>
    <fullName>Hide_Help_Dialog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide_Help_Dialog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BracketsPredictionsController.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

public with sharing class BracketsPredictionsController {
    public Boolean showTree { get; set; }
    public String singleRound { get; set; }
    public String targetPool { get; set; }
    public Brackets_UserTournament__c target { get; set; }

    public String json { get; set; }
    public String message { get; set; }
    public String messageType { get; set; }

    public Boolean hideDialog { get; set; }

    //pool type --
    public Boolean isFullTournament { get; set; }

    //might be locked for any number of reasons
    public Boolean isLocked { get; set; }

    //useful for both full tournament and round by round pools
    public Datetime nextDeadline { get; set; }
    public String formattedNextDeadline { get; set; }

    //for round by round pools, it indicates the active round
    public Integer activeRound { get; set; }

    //for viewing another person's predictions
    public Id targetUserTournament { get; set; }
    public String userTournamentUser { get; set; }

    /**
     *   Constructor
     */
    public BracketsPredictionsController() {
        targetPool = Apexpages.currentPage().getParameters().get('show');
        if (targetPool == null) {
            targetUserTournament = Apexpages.currentPage()
                .getParameters()
                .get('view');
        }
        showTree = false;
        List<Brackets_UserTournament__c> userTournaments = this.userJoinedPools();
        this.singleRound = null;
        if (userTournaments.size() == 1) {
            target = userTournaments.get(0);
            targetPool = target.Brackets_Group__c;
            this.singleRound = target.Brackets_Group__c;
            initNextDeadline();
            if (targetUserTournament == null) {
                BracketsSettings2__c settings = BracketsSettings2__c.getInstance(
                    UserInfo.getUserId()
                );
                if (settings != null) {
                    hideDialog = settings.Hide_Help_Dialog__c;
                }
                showTree = true;
            } else {
                if (this.isLocked) {
                    showTree = true;
                } else {
                    this.message = 'Cannot view a prediction tree before the deadline.';
                    showTree = false;
                }
                this.userTournamentUser = target.User__r.Name;
                hideDialog = true;
            }
        }
    }

    public PageReference goToPoolList() {
        return Page.BracketsPools;
    }

    public PageReference gotoPoolDetail() {
        return new ApexPages.Pagereference('/' + targetPool);
    }

    /**
     * Get the User joined Pools
     * @return UserTournament List
     */
    public List<Brackets_UserTournament__c> userJoinedPools() {
        List<Brackets_UserTournament__c> userTournaments = null;

        if (targetPool == null && targetUserTournament == null) {
            userTournaments = [
                SELECT
                    Id,
                    Brackets_Group__c,
                    Brackets_Group__r.TournamentType__c,
                    Brackets_Group__r.Name,
                    Brackets_Group__r.Type__c,
                    Brackets_Tournament__r.Name,
                    Brackets_Tournament__r.Deadline__c,
                    Championship_Point_Prediction__c
                FROM Brackets_UserTournament__c
                WHERE User__c = :Userinfo.getUserId()
            ];
        } else if (targetUserTournament != null && targetPool == null) {
            userTournaments = [
                SELECT
                    Id,
                    Brackets_Group__c,
                    Brackets_Group__r.TournamentType__c,
                    Brackets_Group__r.Name,
                    Brackets_Group__r.Type__c,
                    Brackets_Tournament__r.Name,
                    Brackets_Tournament__r.Deadline__c,
                    User__r.Name,
                    Championship_Point_Prediction__c
                FROM Brackets_UserTournament__c
                WHERE Id = :targetUserTournament
            ];
        } else {
            userTournaments = [
                SELECT
                    Id,
                    Brackets_Group__c,
                    Brackets_Group__r.TournamentType__c,
                    Brackets_Group__r.Name,
                    Brackets_Group__r.Type__c,
                    Brackets_Tournament__r.Name,
                    Brackets_Tournament__r.Deadline__c,
                    Championship_Point_Prediction__c
                FROM Brackets_UserTournament__c
                WHERE
                    Brackets_Group__c = :targetPool
                    AND User__c = :Userinfo.getUserId()
            ];
        }

        return userTournaments;
    }

    /**
     * Parse string and save predictions
     */

    public PageReference saveAllPred() {
        PageReference page = null;

        if (!isLocked) {
            try {
                if (this.json.length() > 0) {
                    BracketsMatchesPredictionUtil.saveFromJSON(
                        this.json,
                        Userinfo.getUserId()
                    );
                }
                System.debug('12345' + target);
                update target;
                //init();
                this.message = 'All your predictions has been saved successfully!!';
                this.messageType = 'success';
                page = new PageReference(
                    '/apex/BracketsMatchesPrediction?show=' + this.targetPool
                );
                page.setRedirect(true);
            } catch (Exception e) {
                System.debug('exception1:' + e);
                this.message = e.getMessage();
                this.messageType = 'error';
            }
        } else {
            this.messageType = 'locked';
            this.message = 'Predictions are currently locked.';
        }

        updateHideDialog();

        return null;
        //return page;
    }

    public void initNextDeadline() {
        isLocked = false;

        if (
            target.Brackets_Group__r.Type__c ==
            BracketsGroupUtilities.BET_TYPE_FULL_TOURNAMENT
        ) {
            isFullTournament = true;
            nextDeadline = target.Brackets_Tournament__r.Deadline__c;
            if (nextDeadline < Datetime.now()) {
                isLocked = true;
            }
        } else {
            //figure out the next deadline based on
            isFullTournament = false;
            List<Brackets_Round__c> rounds = [
                SELECT Id, Name, Deadline__c, RoundNumber__c
                FROM Brackets_Round__c
                WHERE
                    Brackets_Tournament__c = :target.Brackets_Tournament__c
                    AND Deadline__c > :Datetime.now()
                LIMIT 1
            ];
            if (rounds.size() == 0) {
                isLocked = true;
            } else {
                Brackets_Round__c r = rounds.get(0);
                nextDeadline = r.Deadline__c;
                activeRound = Integer.valueOf('' + r.RoundNumber__c);
            }
        }

        //we should have a deadline and if we don't that's problematic
        if (!isLocked && nextDeadline == null) {
            throw new BracketsException(
                'Unable to initialize the next deadline.  For Full Tournament pools, this is on the Tournament Object.  For Round By Round pools, this is on the individual Round.'
            );
        }

        if (isLocked) {
            formattedNextDeadline = 'Locked';
        } else {
            //get the current users' timezone setting
            User current = [
                SELECT Id, TimeZoneSidKey
                FROM User
                WHERE Id = :UserInfo.getUserId()
            ];
            //now make sure the deadline is in the current users' Z
            formattedNextDeadline = nextDeadline.format(
                'EEE, d MMM yyyy HH:mm a',
                current.TimeZoneSidKey
            );
        }
    }

    public void updateHideDialog() {
        System.debug('Update Hide Dialog' + this.hideDialog);

        if (this.hideDialog == null) {
            this.hideDialog = false;
        }

        BracketsSettings2__c settings = BracketsSettings2__c.getInstance(
            UserInfo.getUserId()
        );
        if (settings == null) {
            settings = new BracketsSettings2__c();
            settings.Name = UserInfo.getUserId();
        }
        settings.Hide_Help_Dialog__c = this.hideDialog;
        upsert settings;
    }

    public String getLastChatterUpdate() {
        String ret = new BracketsFeedItemUtility()
            .getLastTournamentGroupChatter(target.Brackets_Group__c, 75);

        if (ret == '') {
            ret = 'No updates yet - be the first!';
        }
        return ret;
    }
}