force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsUserTournamentUtilitiesTest.cls
@isTest
class BracketsUserTournamentUtilitiesTest {
    @isTest
    static void allMethods() {
        delete [SELECT id FROM Brackets_UserTournament__c];
        Brackets_UserTournament__c userTournamentRetrieved;
        Brackets_Tournament__c myTour = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c myGroup = BracketsTestUtilities.getGroup(myTour.Id);
        Brackets_UserTournament__c uTour = BracketsTestUtilities.createUserTournament(
            UserInfo.getUserId(),
            myTour.Id,
            myGroup.Id
        );

        List<Brackets_UserTournament__c> userTournaments = BracketsUserTournamentUtilities.getUserTournaments(
            myTour.Id,
            myGroup.Id,
            UserInfo.getUserId()
        );
        System.assert(
            !userTournaments.isEmpty(),
            'Should have a user tournament with group ' +
            myGroup.Id +
            ' and tournament ' +
            myTour.Id
        );
        userTournamentRetrieved = userTournaments.get(0);
        System.assert(userTournamentRetrieved.Id == uTour.Id);

        userTournaments = BracketsUserTournamentUtilities.getUserTournamentsFromUser(
            UserInfo.getUserId()
        );
        System.assert(
            !userTournaments.isEmpty(),
            'Should have a user tournament with group ' +
            myGroup.Id +
            ' and tournament ' +
            myTour.Id
        );

        BracketsUserTournamentUtilities.save(userTournaments);
        BracketsUserTournamentUtilities.checkJoinedTournaments(userTournaments);
        BracketsUserTournamentUtilities.userSuscribe(userTournaments);
    }
}