force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsGroupUtilitiesTest.cls
@isTest
class BracketsGroupUtilitiesTest {
    @isTest
    static void testBasics() {
        System.assert(BracketsGroupUtilities.BET_TYPE_BY_ROUND != null);
        System.assert(BracketsGroupUtilities.BET_TYPE_FULL_TOURNAMENT != null);
    }

    @isTest
    static void testGetGroups() {
        BracketsTournamentUtilities.CreatingTournamentTree = true;
        //Create a user
        User testUser = BracketsTestUtilities.createUser();

        System.runAs(testUser) {
            Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
                'Test1 RoundByRound',
                4
            );

            List<Id> ts = new List<Id>();
            ts.add(tournament.Id);

            Brackets_Group__c groupA = BracketsTestUtilities.getGroup(
                tournament.Id,
                BracketsGroupUtilities.BET_TYPE_BY_ROUND
            );
            Brackets_Group__c groupB = BracketsTestUtilities.getGroup(
                tournament.Id,
                BracketsGroupUtilities.BET_TYPE_BY_ROUND
            );

            Brackets_UserTournament__c userTournament = BracketsTestUtilities.createUserTournament(
                Userinfo.getUserId(),
                tournament.Id,
                groupA.Id
            );

            Map<Id, List<Brackets_Group__c>> results = BracketsGroupUtilities.getGroups(
                ts,
                testUser.id
            );

            System.assert(results != null);
            System.assert(results.get(tournament.id) != null);
            System.assert(results.get(tournament.id).size() == 1);

            Map<Id, List<Brackets_Group__c>> results2 = BracketsGroupUtilities.getGroups(
                ts,
                null
            );

            System.assert(results2 != null);
            System.assert(results2.get(tournament.id) != null);
            System.assert(results2.get(tournament.id).size() == 2);

            //just get the group
            List<Brackets_Group__c> groups = BracketsGroupUtilities.getGroups(
                tournament.id,
                testUser.id
            );
            System.assert(groups.size() == 1);
        }

    }
}