force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/Brackets_Round__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Round__c</fullName>
    <label>Round</label>
    <referenceTo>Brackets_Round__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/Brackets_Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/Brackets_UserMatchPred__c.object-meta.xml
<CustomObject>
    <label>UserMatchPrediction</label>
    <nameField>
        <displayFormat>UMP-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserMatchPredictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_Match__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Match__c</fullName>
    <label>Match</label>
    <referenceTo>Brackets_Match__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/Brackets_UserTournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_UserTournament__c</fullName>
    <label>UserTournament</label>
    <referenceTo>Brackets_UserTournament__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserMatchPred__c/fields/PredictedWinnerBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>PredictedWinnerBrackets_Team__c</fullName>
    <label>PredictedWinnerTeam</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>UserMatchPredictions</relationshipLabel>
    <relationshipName>UserMatchPredictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsUserMatchJSONObjectHandlerTest.cls
@isTest
class BracketsUserMatchJSONObjectHandlerTest {
    @isTest
    static void testProcessJSON() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c groupp = BracketsTestUtilities.getGroup(
            tournament.Id
        );
        Brackets_Team__c teamA = BracketsTestUtilities.createTeam('A-Team');
        Brackets_Team__c teamB = BracketsTestUtilities.createTeam('B-Team');

        List<Brackets_Team__c> auxList = new List<Brackets_Team__c>();
        auxList.add(teamA);
        auxList.add(teamB);
        upsert auxList;

        Brackets_Round__c round = BracketsTestUtilities.createSimpleRound(
            tournament
        );
        Brackets_Match__c match = BracketsTestUtilities.createMatch(
            teamA,
            teamB,
            round,
            null
        );
        Brackets_UserTournament__c userTournament = BracketsTestUtilities.createUserTournament(
            Userinfo.getUserId(),
            tournament.Id,
            groupp.Id
        );
        String jsonString =
            '{ "0" : { "matchId" : "' +
            match.Id +
            '" ,"userTour" : "' +
            userTournament.Id +
            '", "teamId" : "' +
            teamA.Id +
            '" , "userPred" : "" }}';

        BracketsUserMatchJSONObjectHandler handler = new BracketsUserMatchJSONObjectHandler();
        handler.processJSON(jsonString);
        System.assert(
            handler.matchesPredictionList.size() == 1,
            'Should have a user match prediction empty at least.'
        );
        Brackets_UserMatchPred__c prediction = handler.matchesPredictionList.get(
            0
        );
        System.assert(
            prediction.Brackets_Match__c == match.Id &&
            prediction.Brackets_UserTournament__c == userTournament.Id &&
            prediction.PredictedWinnerBrackets_Team__c == teamA.Id,
            'This prediction should have a match ' +
            match.Id +
            ' ,an userTournament ' +
            userTournament.Id +
            ' and a predictedWinnerTeam ' +
            teamA.Id
        );
    }

    @isTest
    static void testProcessWrongJSON() {
        String jsonString = ' "0" : { "matchId" : "" ,"userTour" : "", "teamId" : "" , "userPred" : "" }}';
        BracketsUserMatchJSONObjectHandler handler = new BracketsUserMatchJSONObjectHandler();
        try {
            handler.processJSON(jsonString);
            System.assert(false, 'This line shouldn\'t be executed');
        } catch (Exception e) {
            System.assert(
                true,
                'An error should happen when parsing the JSON.'
            );
        }
    }
}