force-app/main/default/objects/Brackets_Group__c/Brackets_Group__c.object-meta.xml
<CustomObject>
    <label>Pool</label>
    <nameField>
        <label>Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Group__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>Pools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/Brackets_UserTournament__c.object-meta.xml
<CustomObject>
    <label>Pool Members</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pool Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Group__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Group__c</fullName>
    <label>Pool</label>
    <referenceTo>Brackets_Group__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_UserTournament__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipName>UserTornaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BracketsPoolControllerTest.cls
@isTest
class BracketsPoolControllerTest {
    @isTest
    static void testTournamentTypes() {
        delete [SELECT Id FROM Brackets_Group__c];
        Brackets_Tournament__c myTour = BracketsTestUtilities.getNewStandardTournament();
        Brackets_Group__c myOpenedGroup = BracketsTestUtilities.getGroup(
            myTour.Id
        );
        upsert myOpenedGroup;
        Brackets_Group__c myClosedGroup = BracketsTestUtilities.getClosedGroup(
            myTour.Id
        );
        Brackets_UserTournament__c uTour = BracketsTestUtilities.createUserTournament(
            UserInfo.getUserId(),
            myTour.Id,
            myOpenedGroup.Id
        );
        BracketsTestUtilities.createUserMatchPrediction(
            myTour.Id,
            myOpenedGroup.Id,
            uTour.Id
        );
        BracketsPoolController controller = new BracketsPoolController();
        Boolean testBool = controller.getCanCreate();
        PageReference testPage = controller.createNewPool();
        testBool = BracketsPoolController.checkObjectCrud('Brackets_Group__c');

        BracketsPoolController.GroupWrap innerClass = new BracketsPoolController.GroupWrap(
            myOpenedGroup
        );
        String testStr = innerClass.getStatus();
        innerClass.hasUserTournaments = true;
        testStr = innerClass.getStatus();

        System.assert(
            controller.groups.size() == 2,
            'The number of groups should be two.'
        );
    }
}