force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/isChild__c.field-meta.xml
<CustomField>
    <fullName>isChild__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled if a tournament is imported from a URL</description>
    <label>isChild</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/TeamCount__c.field-meta.xml
<CustomField>
    <fullName>TeamCount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Number of teams that participate in the tournament</inlineHelpText>
    <label>Team Count</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Which type of tournament this is?

Types supported include: &quot;NFL Playoff&quot; with fixed 12 teams and &quot;Standard&quot; a single elimination type of tournament.</inlineHelpText>
    <label>Type</label>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NFL Playoff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

force-app/main/default/classes/BracketsTournamentUtilitiesTest.cls
@isTest
class BracketsTournamentUtilitiesTest {
    @isTest
    static void testRoundCount() {
        system.assert(BracketsTournamentUtilities.roundCount(4) == 2);
        system.assert(BracketsTournamentUtilities.roundCount(5) == 0);
        system.assert(BracketsTournamentUtilities.roundCount(32) == 5);
    }

    @isTest
    static void testCreateTournamentTree() {
        Brackets_Tournament__c tournament = new Brackets_Tournament__c();
        tournament.Name = 'Test';
        tournament.TeamCount__c = 8;

        insert tournament;

        system.assert(tournament.Id != null);
    }

    @isTest
    static void testCreateNFLPlayoffs() {
        Brackets_Tournament__c tournament = new Brackets_Tournament__c();
        tournament.Name = 'Test';
        tournament.Type__c = BracketsTournamentUtilities.NFL_PLAYOFF_TOURNAMENT_TYPE;

        insert tournament;

        system.assert(tournament.Id != null);
    }

    @isTest
    static void testCheckTeamCountNotUpdateable() {
        Brackets_Tournament__c tournament = new Brackets_Tournament__c();
        tournament.Name = 'Test';
        tournament.Type__c = BracketsTournamentUtilities.NFL_PLAYOFF_TOURNAMENT_TYPE;

        insert tournament;

        tournament.TeamCount__c = 18;

        try {
            upsert tournament;
        } catch (DmlException e) {
            system.assert(
                e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')
            );
        }
    }

    @isTest
    static void testTournamentList() {
        BracketsTournamentUtilities.CreatingTournamentTree = true;

        Brackets_Tournament__c tournament = new Brackets_Tournament__c();
        tournament.Name = 'Test';
        tournament.Type__c = BracketsTournamentUtilities.NFL_PLAYOFF_TOURNAMENT_TYPE;
        tournament.isChild__c = true;
        insert tournament;

        List<ID> ids = new List<ID>();
        ids.add(tournament.id);

        List<Brackets_Tournament__c> tours = BracketsTournamentUtilities.getTournamentList(
            ids
        );
        System.assert(tours.size() == 1);
        System.assert(tours.get(0).name == tournament.name);

        List<Brackets_Tournament__c> tours2 = BracketsTournamentUtilities.getTournamentList(
            1
        );
        System.assert(tours2.size() == 1);
    }
}