force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/isChild__c.field-meta.xml
<CustomField>
    <fullName>isChild__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled if a tournament is imported from a URL</description>
    <label>isChild</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BracketsImportTournamentControllerTest.cls
@isTest
class BracketsImportTournamentControllerTest {
    @isTest
    static void testManualUpdate() {
        Brackets_Tournament__c t = BracketsTestUtilities.createFullTournament(
            4,
            BracketsTournamentUtilities.STANDARD_TOURNAMENT_TYPE
        );
        t.isChild__c = true;
        upsert t;
        Apexpages.currentPage().getParameters().put('tId', t.Id);
        BracketsImportTournamentController c = new BracketsImportTournamentController();

        //test tournament list
        List<Brackets_Tournament__c> ts = c.getTList();
        System.assert(ts.size() > 0);

        //test manu update
        c.doManualUpdate();
        System.assert(c.xmlMessage != null);

        //test garbage URL
        c.importTournament();
        System.assert(c.xmlMessage != null);

        //test http
        c.sourceUrl = 'http://garbage.c';
        c.importTournament();
        System.assert(c.xmlMessage != null);
    }
}