force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/isChild__c.field-meta.xml
<CustomField>
    <fullName>isChild__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled if a tournament is imported from a URL</description>
    <label>isChild</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Update_Source__c.field-meta.xml
<CustomField>
    <fullName>Update_Source__c</fullName>
    <label>Update Source</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BracketsProcessUpdateTest.cls
@isTest
class BracketsProcessUpdateTest {
    @isTest
    static void test2() {
        Brackets_Tournament__c myTour = BracketsTestUtilities.createFullTournament(
            2,
            BracketsTournamentUtilities.DEFAULT_TOURNAMENT_TYPE
        );
        myTour.isChild__c = true;
        myTour.Update_Source__c = 'http://www.salesforce.com';
        update myTour;
        List<Brackets_Tournament__c> myTourList = new List<Brackets_Tournament__c>{
            myTour
        };

        Test.startTest();
        BracketsProccessUpdate cTest = new BracketsProccessUpdate(myTour.Id);

        System.assert(cTest.tourament != null);
        Test.stopTest();
    }

    @isTest
    static void test3() {
        Brackets_Tournament__c myTour = BracketsTestUtilities.createFullTournament(
            2,
            BracketsTournamentUtilities.DEFAULT_TOURNAMENT_TYPE
        );
        myTour.isChild__c = true;
        myTour.Update_Source__c = 'http://www.salesforce.com';
        update myTour;
        List<Brackets_Tournament__c> myTourList = new List<Brackets_Tournament__c>{
            myTour
        };

        Test.startTest();
        BracketsProccessUpdate.processSingleUpdate(myTour.Update_Source__c);
        System.assert(myTour != null);
        Test.stopTest();
    }

    @isTest
    static void test4() {
        Brackets_Tournament__c myTour = BracketsTestUtilities.createFullTournament(
            2,
            BracketsTournamentUtilities.DEFAULT_TOURNAMENT_TYPE
        );
        myTour.isChild__c = true;
        myTour.Update_Source__c = 'http://www.salesforce.com';
        update myTour;
        List<Brackets_Tournament__c> myTourList = new List<Brackets_Tournament__c>{
            myTour
        };

        Test.startTest();
        BracketsProccessUpdate.proccessMultipleUpdate(myTourList);
        System.assert(myTour != null);
        Test.stopTest();
    }
}