force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/Allow_Update__c.field-meta.xml
<CustomField>
    <fullName>Allow_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText
    >Deadline for the &quot;Full tournament&quot; type pools.</inlineHelpText>
    <label>Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/TeamCount__c.field-meta.xml
<CustomField>
    <fullName>TeamCount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Number of teams that participate in the tournament</inlineHelpText>
    <label>Team Count</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Which type of tournament this is?

Types supported include: &quot;NFL Playoff&quot; with fixed 12 teams and &quot;Standard&quot; a single elimination type of tournament.</inlineHelpText>
    <label>Type</label>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NFL Playoff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BracketsSitesTournamentPublisherTest.cls
@isTest
class BracketsSitesTournamentPublisherTest {
    //-------------------------------------------------------------------------
    // Test methods
    //-------------------------------------------------------------------------

    @isTest
    static void testGetOutputXml() {
        BracketsTournamentUtilities.CreatingTournamentTree = true;

        Brackets_Tournament__c tournament = new Brackets_Tournament__c();
        tournament.Name = 'Test';
        tournament.TeamCount__c = 4;
        tournament.Type__c = 'Standard';
        tournament.Deadline__c = Datetime.now();
        tournament.Allow_Update__c = true;
        tournament.Version__c = 2;

        insert tournament;

        Apexpages.currentPage().getParameters().put('id', tournament.Id);
        Apexpages.currentPage().getParameters().put('tVersion', '1');
        BracketsSitesTournamentPublisher ut = new BracketsSitesTournamentPublisher();
        system.assert(ut.getOutputXml() != '');

        system.debug(LoggingLevel.Info, ut.getOutputXml());

        BracketsImportTournament importTour = new BracketsImportTournament(
            null
        );

        importTour.readingTournamentData(ut.getOutputXml());
        Brackets_Tournament__c t = importTour.tournament;
        system.debug(LoggingLevel.Info, t);
        System.assert(t.deadline__c != null);
    }
}