force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/Brackets_Round__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Round__c</fullName>
    <label>Round</label>
    <referenceTo>Brackets_Round__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/FollowingBrackets_Match__c.field-meta.xml
<CustomField>
    <fullName>FollowingBrackets_Match__c</fullName>
    <label>FollowingMatch</label>
    <referenceTo>Brackets_Match__c</referenceTo>
    <relationshipLabel>PreviousMatches</relationshipLabel>
    <relationshipName>PreviousMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/HomeBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>HomeBrackets_Team__c</fullName>
    <label>Team 1</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>HomeMatches</relationshipLabel>
    <relationshipName>HomeMatch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/HomeScore__c.field-meta.xml
<CustomField>
    <fullName>HomeScore__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Score of Team 1 after the match end.</inlineHelpText>
    <label>Team 1 Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <inlineHelpText>Date of the match</inlineHelpText>
    <label>Schedule</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/VisitorBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>VisitorBrackets_Team__c</fullName>
    <label>Team 2</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>VisitorMatches</relationshipLabel>
    <relationshipName>VisitorMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/VisitorScore__c.field-meta.xml
<CustomField>
    <fullName>VisitorScore__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Score of Team 2 after the match end.</inlineHelpText>
    <label>Team 2 Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/WinnerBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>WinnerBrackets_Team__c</fullName>
    <inlineHelpText>Match winner (Team 1 or Team 2)</inlineHelpText>
    <label>Winner Team</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>WinnerMatches</relationshipLabel>
    <relationshipName>WinnerMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/Brackets_Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BracketsMatchUtilitiesTest.cls
@isTest
class BracketsMatchUtilitiesTest {
    //-------------------------------------------------------------------------
    // Test Methods
    //-------------------------------------------------------------------------

    @isTest
    static void testDateMatchesValidation() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Checking dates',
            2
        );
        Brackets_Round__c round = BracketsTestUtilities.createRound(
            tournament,
            1,
            DateTime.now(),
            3,
            'First Round'
        );

        Brackets_Team__c homeTeam, visitorTeam;
        List<Brackets_Match__c> matches = new List<Brackets_Match__c>{
            new Brackets_Match__c(),
            new Brackets_Match__c(),
            new Brackets_Match__c()
        };

        // Standard flow
        matches[0].Schedule__c = DateTime.now().addDays(1);
        matches[0].Brackets_Round__c = round.Id;

        matches[1].Schedule__c = DateTime.now().addDays(2);
        matches[1].Brackets_Round__c = round.Id;

        matches[2].Schedule__c = DateTime.now().addDays(5);
        matches[2].Brackets_Round__c = round.Id;

        insert matches;

        matches[0].FollowingBrackets_Match__c = matches[1].Id;
        matches[1].FollowingBrackets_Match__c = matches[2].Id;

        upsert matches;

        matches[1].Schedule__c = DateTime.now().addDays(3);

        upsert matches;

        system.assert(matches.size() == 3);
    }

    @isTest
    static void testUpdateFollowingMatchesWinner() {
        Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
            'Checking winners',
            2
        );
        Brackets_Round__c firstRound = BracketsTestUtilities.createRound(
            tournament,
            1,
            DateTime.now(),
            3,
            'First Round'
        );
        Brackets_Round__c secondRound = BracketsTestUtilities.createRound(
            tournament,
            2,
            DateTime.now().addDays(5),
            5,
            'Second Round'
        );
        List<Brackets_Team__c> teams = BracketsTestUtilities.createTeamList(2);
        insert teams;

        Brackets_Team__c homeTeam, visitorTeam;
        List<Brackets_Match__c> matches = new List<Brackets_Match__c>{
            new Brackets_Match__c(),
            new Brackets_Match__c()
        };

        matches[0].Brackets_Round__c = firstRound.Id;
        matches[0].HomeBrackets_Team__c = teams[0].Id;
        matches[0].VisitorBrackets_Team__c = teams[1].Id;
        matches[1].Brackets_Round__c = secondRound.Id;
        insert matches;

        matches[0].FollowingBrackets_Match__c = matches[1].Id;
        matches[0].HomeScore__c = 25;
        matches[0].VisitorScore__c = 24;
        matches[0].WinnerBrackets_Team__c = teams[0].Id;
        update matches[0];

        Map<Id, Brackets_Match__c> matchesMap = new Map<Id, Brackets_Match__c>();
        matchesMap.put(matches[0].Id, matches[0]);
        System.assert(
            matches[0].HomeBrackets_Team__c == matches[0].WinnerBrackets_Team__c
        );

        //check the first level completed for the matches[0]
        try {
            BracketsMatchUtilities.checkFirstLevelCompleted(
                tournament,
                matchesMap
            );
            System.assert(true, 'This line should be executed.');
        } catch (Exception e) {
            System.assert(false, 'This line shouldn\'t be executed.');
        }

        matchesMap.put(matches[1].Id, matches[1]);
        //check the first level completed for the whole matches
        try {
            BracketsMatchUtilities.checkFirstLevelCompleted(
                tournament,
                matchesMap
            );
            System.assert(false, 'This line shouldn\'t be executed.');
        } catch (Exception e) {
            System.assert(true, 'This line should be executed.');
        }
    }
}