force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/Brackets_Round__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Round__c</fullName>
    <label>Round</label>
    <referenceTo>Brackets_Round__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/Brackets_Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BracketsTeamUtilitiesTest.cls
@isTest
class BracketsTeamUtilitiesTest {
    @isTest
    static void testCanDeleteTeams() {
        List<Brackets_Team__c> teamList = BracketsTestUtilities.createTeamList(
            10
        );
        upsert teamList;
        //not connected to a tournament so its fine.
        system.assert(BracketsTeamUtilities.canDeleteTeams(teamList));

        BracketsTournamentUtilities.CreatingTournamentTree = true;
        //Create a user
        User testUser = BracketsTestUtilities.createUser();

        System.runAs(testUser) {
            Brackets_Tournament__c tournament = BracketsTestUtilities.createTournament(
                'Test1 RoundByRound',
                4
            );
            Brackets_Team__c teamA = BracketsTestUtilities.createTeam('A-Team');

            List<Brackets_Team__c> auxList = new List<Brackets_Team__c>();
            auxList.add(teamA);
            upsert auxList;

            Brackets_Round__c round = BracketsTestUtilities.createRound(
                tournament,
                1,
                null,
                4,
                'Round1-Test'
            );
            Brackets_Match__c match = BracketsTestUtilities.createMatch(
                teamA,
                null,
                round,
                BracketsTournamentUtilities.NFL_CONFERENCE_AMERICAN
            );

            system.assert(!BracketsTeamUtilities.canDeleteTeams(auxList));

            //so now test the trigger
            try {
                delete teamA;
                System.assert(false);
            } catch (Exception e) {
                //correct
            }
        }
    }
}