force-app/main/default/objects/Brackets_Match__c/Brackets_Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Match__c/fields/Brackets_Round__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Round__c</fullName>
    <label>Round</label>
    <referenceTo>Brackets_Round__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/Conference__c.field-meta.xml
<CustomField>
    <fullName>Conference__c</fullName>
    <inlineHelpText
    >If rounds are grouped in conferences, this is the conference the match is part of.</inlineHelpText>
    <label>Conference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Short description of the match</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/FollowingBrackets_Match__c.field-meta.xml
<CustomField>
    <fullName>FollowingBrackets_Match__c</fullName>
    <label>FollowingMatch</label>
    <referenceTo>Brackets_Match__c</referenceTo>
    <relationshipLabel>PreviousMatches</relationshipLabel>
    <relationshipName>PreviousMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/FollowingIsHome__c.field-meta.xml
<CustomField>
    <fullName>FollowingIsHome__c</fullName>
    <defaultValue>true</defaultValue>
    <label>FollowingIsHome</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/HomeBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>HomeBrackets_Team__c</fullName>
    <label>Team 1</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>HomeMatches</relationshipLabel>
    <relationshipName>HomeMatch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/HomeScore__c.field-meta.xml
<CustomField>
    <fullName>HomeScore__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Score of Team 1 after the match end.</inlineHelpText>
    <label>Team 1 Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <defaultValue>1</defaultValue>
    <description
    >Keep the position respect to its round, each position should be unique.</description>
    <label>Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <inlineHelpText>Date of the match</inlineHelpText>
    <label>Schedule</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/VisitorBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>VisitorBrackets_Team__c</fullName>
    <label>Team 2</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>VisitorMatches</relationshipLabel>
    <relationshipName>VisitorMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/VisitorScore__c.field-meta.xml
<CustomField>
    <fullName>VisitorScore__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Score of Team 2 after the match end.</inlineHelpText>
    <label>Team 2 Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Match__c/fields/WinnerBrackets_Team__c.field-meta.xml
<CustomField>
    <fullName>WinnerBrackets_Team__c</fullName>
    <inlineHelpText>Match winner (Team 1 or Team 2)</inlineHelpText>
    <label>Winner Team</label>
    <referenceTo>Brackets_Team__c</referenceTo>
    <relationshipLabel>WinnerMatches</relationshipLabel>
    <relationshipName>WinnerMatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/Brackets_Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Round__c/fields/Brackets_Tournament__c.field-meta.xml
<CustomField>
    <fullName>Brackets_Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Brackets_Tournament__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText
    >Last date to make predictions for the round.</inlineHelpText>
    <label>Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <inlineHelpText
    >End date of the round, calculated with the date of the last match.</inlineHelpText>
    <label>End</label>
    <summarizedField>Brackets_Match__c.Schedule__c</summarizedField>
    <summaryForeignKey>Brackets_Match__c.Brackets_Round__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/RoundNumber__c.field-meta.xml
<CustomField>
    <fullName>RoundNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Number indicating the position of the round, being 1 the first round</inlineHelpText>
    <label>Round Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/ScorePoints__c.field-meta.xml
<CustomField>
    <fullName>ScorePoints__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Points a user wins for each correct prediction in the round</inlineHelpText>
    <label>Score Points</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Round__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <inlineHelpText
    >Start date of the round, calculated with the date of the first match.</inlineHelpText>
    <label>Start</label>
    <summarizedField>Brackets_Match__c.Schedule__c</summarizedField>
    <summaryForeignKey>Brackets_Match__c.Brackets_Round__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/Brackets_Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Team__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Team full description</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brackets_Team__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/Brackets_Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brackets_Tournament__c/fields/Allow_Update__c.field-meta.xml
<CustomField>
    <fullName>Allow_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText
    >Deadline for the &quot;Full tournament&quot; type pools.</inlineHelpText>
    <label>Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>General description of the tournament.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <inlineHelpText
    >Tournament end date, calculated with the date of the last match played</inlineHelpText>
    <label>End Date</label>
    <summarizedField>Brackets_Round__c.End__c</summarizedField>
    <summaryForeignKey
    >Brackets_Round__c.Brackets_Tournament__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <inlineHelpText
    >Tournament start date, calculated with the date of the first match played</inlineHelpText>
    <label>Start Date</label>
    <summarizedField>Brackets_Round__c.Start__c</summarizedField>
    <summaryForeignKey
    >Brackets_Round__c.Brackets_Tournament__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/TeamCount__c.field-meta.xml
<CustomField>
    <fullName>TeamCount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText
    >Number of teams that participate in the tournament</inlineHelpText>
    <label>Team Count</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Which type of tournament this is?

Types supported include: &quot;NFL Playoff&quot; with fixed 12 teams and &quot;Standard&quot; a single elimination type of tournament.</inlineHelpText>
    <label>Type</label>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NFL Playoff</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Update_Source__c.field-meta.xml
<CustomField>
    <fullName>Update_Source__c</fullName>
    <label>Update Source</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Brackets_Tournament__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BracketsSitesTournamentPublisher.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

public with sharing class BracketsSitesTournamentPublisher {
    private Brackets_Tournament__c tournament;

    public BracketsSitesTournamentPublisher() {
        this.tournament = this.getTournament();
    }

    /**
     * Retrive last update from the refered tournament
     * @return oXml : Returns the XML Body;
     */
    public String getOutputXml() {
        String result;
        if (this.tournament.Id == null) {
            System.debug('1234 is null');
            result = this.getXmlError();
        } else {
            System.debug('1234tournament id is not null');
            result = this.getTournamentXml();
        }
        return result;
    }

    /**
     * Get Brackets_Tournament__c object
     * @return tournament
     */
    private Brackets_Tournament__c getTournament() {
        Brackets_Tournament__c ret = [
            SELECT
                t.TeamCount__c,
                t.Start__c,
                t.Name,
                t.Id,
                t.ExternalId__c,
                t.End__c,
                t.Description__c,
                t.Version__c,
                t.Allow_Update__c,
                t.Update_Source__c,
                t.Type__c,
                Deadline__c
            FROM Brackets_Tournament__c t
            WHERE Id = :this.getTournamentId()
        ];

        System.debug('1234 allow update ' + ret.Allow_Update__c);

        return ret;
    }

    /**
     * Return an Error
     * @return oXml
     */
    private String getXmlError() {
        Xmlstreamwriter oXml = new Xmlstreamwriter();
        oXml.writeStartElement(
            null,
            BracketsImportExportUtilities.ERROR_TAG,
            null
        );
        oXml.writeCharacters(BracketsImportExportUtilities.MISSING_TOURNAMENT);
        oXml.writeEndElement();
        oXml.writeEndDocument();
        return oXml.getXmlString();
    }

    /**
     *   Check if exist an parameter json in the headers
     */
    private Boolean hasUserStatistic() {
        return Apexpages.currentPage().getHeaders().get('json') != null;
    }

    /**
     * Method in charge of compiling XML document
     * @return ret : Write a XML Body then return it
     */
    private String getTournamentXml() {
        Xmlstreamwriter out = new Xmlstreamwriter();
        out.writeStartDocument(null, '1.0');
        System.debug(
            '1234 allow update ' +
            tournament.Allow_Update__c +
            ' and version ' +
            tournament.Version__c
        );
        if (
            tournament.Allow_Update__c &&
            tournament.Version__c > this.getClientVersion()
        ) {
            BracketsExportTeams expTeams = new BracketsExportTeams(
                tournament.Id,
                out
            );
            out.writeStartElement(null, 'export', null);
            out = expTeams.BracketsexportTeams();

            out.writeStartElement(null, 'Tournament', null);

            BracketsImportExportUtilities.writeElement(
                out,
                'id',
                '' + tournament.Id
            );
            //RSC do we need this?
            //BracketsImportExportUtilities.writeElement( out, 'externalId', '' + tournament.ExternalId__c );
            BracketsImportExportUtilities.writeElement(
                out,
                'name',
                '' + tournament.Name
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'description',
                '' + tournament.Description__c
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'teamCount',
                '' + String.valueOf(tournament.TeamCount__c)
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'version',
                '' + tournament.Version__c
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'type',
                '' + tournament.Type__c
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'source',
                '' + tournament.Update_Source__c
            );
            BracketsImportExportUtilities.writeElement(
                out,
                'deadline',
                '' + String.valueOf(tournament.Deadline__c)
            );

            out.writeEndElement();

            List<Brackets_Round__c> rounds = [
                SELECT
                    r.Brackets_Tournament__c,
                    r.Start__c,
                    r.ScorePoints__c,
                    r.RoundNumber__c,
                    r.Name,
                    r.Id,
                    r.ExternalId__c,
                    r.End__c,
                    r.Deadline__c,
                    (
                        SELECT
                            Name,
                            Brackets_Round__c,
                            Conference__c,
                            Description__c,
                            FollowingBrackets_Match__c,
                            FollowingIsHome__c,
                            HomeScore__c,
                            HomeBrackets_Team__c,
                            Schedule__c,
                            VisitorScore__c,
                            VisitorBrackets_Team__c,
                            WinnerBrackets_Team__c,
                            ExternalId__c,
                            Position__c
                        FROM Matches__r
                        ORDER BY Position__c
                    )
                FROM Brackets_Round__c r
                WHERE r.Brackets_Tournament__c = :tournament.Id
                ORDER BY RoundNumber__c
            ];

            //----------------------------------------------------
            List<String> roundIds = new List<String>();
            for (Brackets_Round__c round : rounds) {
                roundIds.add(round.Id);
            }
            Map<Id, Brackets_Match__c> matches = new Map<Id, Brackets_Match__c>(
                [
                    SELECT
                        m.Id,
                        m.Position__c,
                        m.VisitorBrackets_Team__c,
                        m.VisitorBrackets_Team__r.ExternalId__c,
                        m.HomeBrackets_Team__c,
                        m.HomeBrackets_Team__r.ExternalId__c,
                        m.WinnerBrackets_Team__c,
                        m.WinnerBrackets_Team__r.ExternalId__c,
                        m.FollowingBrackets_Match__c,
                        m.FollowingBrackets_Match__r.ExternalId__c,
                        m.Conference__c
                    FROM Brackets_Match__c m
                    WHERE m.Brackets_Round__c IN :roundIds
                    ORDER BY m.Brackets_Round__r.RoundNumber__c, m.Position__c
                ]
            );
            //----------------------------------------------------

            out.writeStartElement(null, 'Rounds', null);
            for (Brackets_Round__c round : rounds) {
                out.writeStartElement(null, 'Round', null);

                BracketsImportExportUtilities.writeElement(
                    out,
                    'id',
                    '' + round.Id
                );
                //RSC Do we need this?
                //BracketsImportExportUtilities.writeElement( out, 'ExternalId', '' + round.ExternalId__c );
                BracketsImportExportUtilities.writeElement(
                    out,
                    'name',
                    '' + round.Name
                );
                BracketsImportExportUtilities.writeElement(
                    out,
                    'deadline',
                    '' + String.valueOf(round.Deadline__c)
                );
                BracketsImportExportUtilities.writeElement(
                    out,
                    'roundNumber',
                    '' + String.valueOf(round.RoundNumber__c)
                );
                BracketsImportExportUtilities.writeElement(
                    out,
                    'scorePoints',
                    '' + String.valueOf(round.ScorePoints__c)
                );
                BracketsImportExportUtilities.writeElement(
                    out,
                    'tournament',
                    '' + round.Brackets_Tournament__c
                );

                out.writeStartElement(null, 'Matches', null);

                for (Brackets_Match__c match : round.Matches__r) {
                    out.writeStartElement(null, 'Match', null);

                    BracketsImportExportUtilities.writeElement(
                        out,
                        'id',
                        '' + match.Id
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'number',
                        '' + match.Name
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'description',
                        '' + match.Description__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'position',
                        '' + match.Position__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'homeScore',
                        '' + String.valueOf(match.HomeScore__c)
                    );

                    BracketsImportExportUtilities.writeElement(
                        out,
                        'homeTeam',
                        '' + matches.get(match.Id).HomeBrackets_Team__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'vistitorTeam',
                        '' + matches.get(match.Id).VisitorBrackets_Team__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'winnerTeam',
                        '' + matches.get(match.Id).WinnerBrackets_Team__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'followingMatch',
                        '' + matches.get(match.Id).FollowingBrackets_Match__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'round',
                        '' + String.valueOf(round.id)
                    );

                    BracketsImportExportUtilities.writeElement(
                        out,
                        'schedule',
                        '' + String.valueOf(match.Schedule__c)
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'visitorScore',
                        '' + String.valueOf(match.VisitorScore__c)
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'conference',
                        '' + match.Conference__c
                    );
                    BracketsImportExportUtilities.writeElement(
                        out,
                        'followingIsHome',
                        '' + String.valueOf(match.FollowingIsHome__c)
                    );

                    out.writeEndElement();
                }

                out.writeEndElement(); //End Matches
                out.writeEndElement(); //End Round
            }

            out.writeEndElement(); //End Rounds
            out.writeEndElement(); //End Export
        } else {
            out.writeStartElement(
                null,
                BracketsImportExportUtilities.ERROR_TAG,
                null
            );
            out.writeCharacters(
                BracketsImportExportUtilities.NOT_UPDATES_FOUND
            );
            out.writeEndElement();
            out.writeEndDocument();
        }
        return out.getXmlString();
    }

    /**
     * Return the related tournament ID
     * @return tournamentId
     */
    public String getTournamentId() {
        String tournamentId = Apexpages.currentPage().getParameters().get('id');
        return tournamentId;
    }

    /**
     * Return the Client Tournament  Version
     * @return version
     */
    public Integer getClientVersion() {
        String ver = Apexpages.currentPage().getParameters().get('tVersion');
        return (ver != null) ? Integer.valueOf(ver) : 0;
    }
}